### ISSUE TITLE
Segmentation fault in icc2

### ISSUE THREAD

**Issue by xpww** [mperov/fixSegfaultVCS#2]
Hello, I followed your instructions in the readme, but gdb did not tell me *.so that I need to patch it. This is my log:

`(base) mrpp@mrpp:~/software/synopsys2022/icc2/T-2022.03/bin$ gdb /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec...
(No debugging symbols found in /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec)
(gdb) set args -shell=icc2
(gdb) run
Starting program: /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec -shell=icc2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff8d3ff700 (LWP 26153)]
Error: Unknown shell.  Use -shell to select one of dcrt dft fc icc2 3dic
[Thread 0x7fff8ddbe280 (LWP 26127) exited]
[Inferior 1 (process 26127) exited with code 01]
(gdb) run -h
Starting program: /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec -h
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff8d3ff700 (LWP 26185)]
Error: Unknown shell.  Use -shell to select one of dcrt dft fc icc2 3dic
[Thread 0x7fff8ddbe280 (LWP 26169) exited]
[Inferior 1 (process 26169) exited with code 01]
(gdb) run -shell icc2
Starting program: /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec -shell icc2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff8d3ff700 (LWP 26239)]
[Thread 0x7fff8d3ff700 (LWP 26239) exited]
process 26220 is executing new program: /home/mrpp/software/synopsys2022/icc2/T-2022.03/linux64/nwtn/bin/dgcom_exec
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x1554ea9ff700 (LWP 26264)]
[New Thread 0x1554e9989700 (LWP 26279)]
[Thread 0x1554e9989700 (LWP 26279) exited]
[New Thread 0x1554e9989700 (LWP 26287)]
[New Thread 0x1554e9550700 (LWP 26316)]
[Thread 0x1554e9989700 (LWP 26287) exited]
ERROR: The application is terminated (Error Code: 501).
Please contact support center at support_center@synopsys.com.

Thread 1 "dgcom_exec" received signal SIGSEGV, Segmentation fault.
0x00000000273ea510 in SNPSee_91ecbd23c4a0f37d9b74954c2e83d4ea28e660b192171022f662109085ab9255 ()
(gdb) backtrace
#0  0x00000000273ea510 in SNPSee_91ecbd23c4a0f37d9b74954c2e83d4ea28e660b192171022f662109085ab9255 ()
#1  0x00000000273ea685 in SNPSee_794e4fbf9dbc95eea4e7c00076e76618 ()
#2  0x00000000273eb145 in SNPSee_ba11b1edbd04051f4cfa1e58091b7b6c ()
#3  0x0000000028c4fce9 in SNPSee_aac57d44e163568190759c9cfe8563709bace0af59e1ec70ddb230f1c8aad2df ()
#4  0x00001554f1f4c8a7 in __run_exit_handlers (status=-1, listp=0x1554f20f2718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#5  0x00001554f1f4ca60 in __GI_exit (status=<optimized out>) at exit.c:139
#6  0x000000002740272e in  ()
#7  0x0000000027407aa8 in SNPSee_02c2e000e122135fdcc20a77ef3b8d15 ()
#8  0x00000000273ef0b5 in SNPSee_b02289328df49303de0a4a986839ba7137fc9785576e580e ()
#9  0x00000000273f13ad in SNPSee_1bc1de7a7892c3dc9ed9fc9f718684af ()
#10 0x00000000273f25ea in SNPSee_4339c3fcb642499431e6499fc1f819f1 ()
#11 0x00000000273ec5a9 in SNPSee_a10369bdf7c5916ddd6866ce7e2e861c ()
#12 0x00000000273ecdc5 in SNPSee_00b1acee80c770570cd75f9efbe24cca ()
#13 0x00000000273ed945 in SNPSee_ba11b1edbd04051f5bb81b1861cdf84a ()
#14 0x0000000028c4c15b in SNPSee_c5dd1896fcdf1fe9c105c3c8e063e45a056f79daeb85cf55380d198817a45afc994f640f09d5e4b45aa7ad8026238725c99349dfd63bfc3f ()
#15 0x0000000028c4e66f in SNPSee_aac57d44e163568190759c9cfe856370ae4235c295d94f6df6c1024e1eceb5d2218b8aef9faa42bfb2d446ff1b00d0810193cc1c5a4a23aaf93239c0660ab7fa472a1c7004d64121e3b3da7ed4e790992df34f2ed621d7fd39d4ab35ca711c51 ()
#16 0x0000000028d31131 in SNPSee_b3a63ca9beb66366a2beecdfa325f5f830d5bf4b8974e747b53590f44785f4a89f60cece70e10e1f40e2a34e0182f044 ()
#17 0x0000000028d35227 in SNPSee_b3a63ca9beb66366a2beecdfa325f5f850e37c16b964335ba934f8a7afefeaf1 ()
#18 0x0000000003e84e82 in SNPSee_6188b3f9a7e769c7eb2dc22ab181ff5c0260e7bf3c6e6c5b6dd310362dd3e58b19a33122e2a80c1014bca5a076370ba0686492d474ef148ca36ababef5945158a888f7e536545dec88d039942c447aad829ec3c9a13ccf1352c7f068f1dc0d713b949058f841385ce96831542394be36f2ec7e463409336ff9646fa385cc5a553df93f9156ead7f8 ()
#19 0x0000000003e8721d in SNPSee_5a24f30b88271223 ()
#20 0x00001554f1f2a083 in __libc_start_main (main=
--Type <RET> for more, q to quit, c to continue without paging--c
    0x3e86800 <SNPSee_5a24f30b88271223>, argc=3, argv=0x7fffffffc858, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc848) at ../csu/libc-start.c:308
#21 0x000000000487b4cc in SNPSee_d06eed713327be76 ()
`

What do I need to do to know which so file needs to be patched?

**Comment by mperov** [comment]
Hello!
This project helps to fix Segfault in VCS and Verdi.
ICC2 is not part of VCS or Verdi.

**Comment by ZhengYANG567** [comment]
Hi I encounter the same issue and this issue continues happening. Have you save this ICC2 issue? Thanks!

**Comment by xpww** [comment]
hi，use the latest https://github.com/BinaryHackerLab/SynopsysMonoSlayer，it works for me发自我的 iPhone在 2024年10月8日，23:20，ZhengYANG567 ***@***.***> 写道：﻿
Hi I encounter the same issue and this issue continues happening. Have you save this ICC2 issue? Thanks!
